# Generated by Django 4.2.2 on 2023-06-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_computer_image_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='computer',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
