# Generated by Django 4.2.2 on 2023-06-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_geeksmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='DetailModel',
        ),
    ]
