# Generated by Django 4.2.2 on 2023-06-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
