# Generated by Django 4.2.2 on 2023-06-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0011_remove_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='computer',
            field=models.IntegerField(),
        ),
    ]
